#!/bin/bash
gsettings set org.gnome.shell favorite-apps "['org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.DiskUtility.desktop', 'install-debian.desktop' ,'firefox-esr.desktop']"
# Die Namen findet man hier!
# cd /usr/share/applications/
# find / |grep org.gnome.Terminal.desktop
