#! /bin/bash

# copyright Andreas Schockenhoff 2001-2025, asc@ekf.de

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

cat <<'EOF' > $target/home/${username}/.bash_aliases
alias menu='echo $PATH | grep :.$ > /dev/null || PATH=$PATH:. && cat menu.txt'  
EOF

cat <<'EOF' > $target/home/${username}/menu.txt
This is a help test for the Menu in this Path.
EOF

exit $error
