#!/bin/bash

# Function to display help message
show_help() {
    echo "Usage: $0 [OPTION]"
    echo "This script demonstrates a help prompt with the following options:"
    echo "  -h, --help, -?    Display this help message"
    echo
    echo "Complete user text for this program:"
    echo "Please write a bash shell script with help promt --help -h -?. Also include this complete copilot prompt into the help section. Also that this script is AI generated."
    echo
    echo "This script was generated by an AI."
}

# Check for help options
case "$1" in
    -h|--help|-\?)
        show_help
        exit 0
        ;;
    *)
        echo "Invalid option. Use -h, --help, or -? for help."
        exit 1
        ;;
esac
