#!/bin/bash
ansible-playbook /home/ansible/debian-lan/installbox.yml  --extra-vars "hostname=installbox domain=test.local" $@
# ansible-playbook /home/ansible/debian-lan/installbox.yml  --extra-vars "hostname=installbox domain=test.local" --inventory=installbox, $@
