#!/bin/bash
ansible-playbook /home/ansible/debian-lan/$1.yml  --extra-vars "hostname=$1 domain=test.local" $1 -i $2
# ansible-playbook /home/ansible/debian-lan/installbox.yml  --extra-vars "hostname=installbox domain=test.local" --inventory=installbox, $@
