#!/bin/bash
sudo apt install mtools
sudo apt install dosfstools

## Creating a FAI-CD ISO image
# Create a partitial mirror containing the packages needed (16s needed)

sudo fai-mirror -cDEFAULT,AMD64,DHCPC,FAIBASE,DEBIAN,DEMO,DEBUG,FAISERVER1,GRUB_PC,LAST /srv/mirror

# Create the ISO image (run this as root)
sudo fai-cd -f -m /srv/mirror /srv/fai-cd.iso

# sudo cp /srv/fai-cd.iso /var/www/helloWWW

# Run the CD in a VM
# fai-kvm -n cd /srv/fai-cd.iso
