#!/bin/bash
echo "Sorry not tested/implemented yet!"
set -o xtrace

cat /proc/sys/net/ipv4/ip_forward

echo "net.ipv4.ip_forward = 1"  >> /etc/sysctl.conf
sysctl -p

cat /proc/sys/net/ipv4/ip_forward

sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables-save > /etc/iptables/rules.v4

iptables -t nat -L

# bei live braucht man leider noch eine /etc/rc.local 
echo "#!/bin/bash"  >> /etc/rc.local
echo "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"  >> /etc/rc.local

